runtime: php74 # Replace with php74 to use PHP 7.4



# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

entrypoint:
    serve handler.php


